### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by CA1012** [FGMEMBERS/Citation#1]
All I ever see when ever i download this plane and spawn is grey windows.(this is with out rembrandt.)

**Comment by legoboyvdlp** [comment]
You need FlightGear 3.7.

**Comment by CA1012** [comment]
i use 3.4

**Comment by FGDATA** [comment]
https://github.com/FGMEMBERS/Citation/releases/tag/FG3.4
That version linked above will work fine for you
