### ISSUE TITLE
Windows shading problem (I use mac so not the OS.)

### ISSUE THREAD

**Issue by CA1012** [FGMEMBERS/Citation#2]
All I ever see when ever i download this plane and spawn is grey windows.(this is with out rembrandt.)

**Comment by FGDATA** [comment]
FG 3.4? FG 3.7?

**Comment by FGDATA** [comment]
In any case, FALCON, I believe what happens is that your version of flightgear is lower than needed for the master branch of this craft. Try out with an older release, you can obtain here:

https://github.com/FGMEMBERS/Citation/releases/tag/FG3.4
